name: {{ project_name }}_dev

packages:
  - frontend
  - server

scripts:
  test: melos exec -c 1  -- "dart test" --fail-fast

  format: melos exec -- "dart format ."

  analyze: melos exec -- "dart analyze . --fatal-infos --no-fatal-warnings"
