name: server
description: A server app using the shelf package and Docker.
version: 1.0.0

environment:
  sdk: ^3.2.0

dependencies:
  args: ^2.4.0
  shelf: ^1.4.0
  shelf_router: ^1.1.0

  dart_firebase_admin: ^0.3.0
  shelf_cors_headers: ^0.1.5
  envied: ^0.5.3

dev_dependencies:
  build_runner: ^2.4.8
  envied_generator: ^0.5.3
  lints: ^2.1.0
