name: globe_ai
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: ^3.4.0

dependencies:
  globe_runtime: ^1.0.0
  path: ^1.9.1
  protobuf: ^3.1.0

dev_dependencies:
  lints: ^5.1.1
  test: ^1.24.0

scripts:
  gen_dart: protoc 
        --dart_out=lib/generated 
        --proto_path=protos protos/*.proto
        google/protobuf/any.proto
  gen_typescript: protoc
        --plugin=protoc-gen-ts_proto=$(which protoc-gen-ts_proto) 
        --ts_out=lib/generated 
        --proto_path=protos protos/*.proto
        google/protobuf/any.proto