name: globe_ai
description: A Dart-first package for interacting with large language models (LLMs) like OpenAI’s GPT series — built specifically for the Globe runtime.
version: 1.0.1
repository: https://github.com/invertase/globe/tree/main/packages/globe_ai

environment:
  sdk: ^3.4.0

dependencies:
  globe_runtime: ^1.0.4
  luthor: ^0.6.1
  path: ^1.9.1
  protobuf: ^3.1.0
  version: ^3.0.2

dev_dependencies:
  lints: ^5.1.1
  test: ^1.24.0
  protoc_plugin: 21.1.2
  rps: ^0.7.0

scripts:
  build: npx tsup
  gen_dart: protoc
    --dart_out=lib/generated
    --proto_path=protos protos/*.proto
  gen_typescript: protoc
    --plugin=protoc-gen-ts_proto=$(which protoc-gen-ts_proto)
    --ts_out=lib/generated
    --proto_path=protos protos/*.proto