name: globe_ai
description: A starting point for Dart libraries or applications.
version: 1.0.0

publish_to: "none" # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ^3.4.0

dependencies:
  globe_runtime:
    # path: "../../../../OpenSource/dart_v8_runtime/packages/globe_runtime"
    git:
      url: https://github.com/invertase/globe_runtime.git
      path: packages/globe_runtime
  luthor: ^0.6.1
  path: ^1.9.1
  protobuf: ^3.1.0

dev_dependencies:
  lints: ^5.1.1
  test: ^1.24.0
  protoc_plugin: 21.1.2

scripts:
  gen_dart: protoc
    --dart_out=lib/generated
    --proto_path=protos protos/*.proto
    # google/protobuf/any.proto
    # google/protobuf/struct.proto
  gen_typescript: protoc
    --plugin=protoc-gen-ts_proto=$(which protoc-gen-ts_proto)
    --ts_out=lib/generated
    --proto_path=protos protos/*.proto
    google/protobuf/any.proto
