name: server
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.3

dependencies:
  args: ^2.4.0
  shelf: ^1.4.0
  shelf_router: ^1.1.0

  dotenv: ^4.2.0
  
  dart_firebase_admin: ^0.3.0
  jwt_decoder: ^2.0.1

dev_dependencies:
  lints: ^2.1.0
  spookie: ^1.0.2+3
