name: ffi_hello_world
description: A sample dart app showing FFI usage on Globe.
version: 1.0.0

environment:
  sdk: ^3.3.1

dependencies:
  shelf: ^1.4.0
  ffi: ^2.1.0
  path: ^1.9.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
