version: '3.8'
services:
  dart-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - dart-pub-cache:/root/.pub-cache

volumes:
  dart-pub-cache:
