name: shelf_rpc
description: Type-safe RPC Shelf Server and Client for Dart.
version: 0.0.1
repository: https://github.com/invertase/globe

environment:
  sdk: ^3.7.0-83.0.dev

dependencies:
  analyzer: ^7.2.0
  build_runner: ^2.4.14
  build: ^2.4.2
  source_gen: ^2.0.0
  path: ^1.9.1
  shelf: ^1.4.2
  dart_style: ^3.0.1
  change_case: ^2.2.0
  http: ^1.3.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
