blank_issues_enabled: false
contact_links:
  - name: Globe Discord Community
    url: https://invertase.link/globe-discord
    about: For questions and support please join our Discord Community.
  - name: Globe X (Twitter)
    url: https://twitter.com/dart_globe
    about: Follow us on Twitter for updates and news.
