name: globe_kv
description: GlobeKV is an eventually-consistent data storage system for storing and retrieving data from a global datastore, designed for high-reads at low latency. 
repository: https://github.com/invertase/globe
version: 1.0.1

environment:
  sdk: ^3.0.0

dependencies:
  collection: ^1.19.1
  http: ^1.2.2
  meta: ^1.16.0
  path: ^1.9.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
