name: globe_kv
description: A starting point for Dart libraries or applications.
repository: https://github.com/invertase/globe
version: 1.0.0

environment:
  sdk: ^3.0.0

dependencies:
  collection: ^1.19.1
  http: ^1.2.2
  meta: ^1.16.0
  path: ^1.9.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
