name: globe_kv_example
description: A server app using the shelf package and Docker.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  globe_kv:
    git:
      url: https://github.com/invertase/globe.git
      path: packages/globe_kv
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  
dev_dependencies:
  lints: ^5.1.1
