name: dart_frog_rest_api
description: Simple DartFrog API
version: 0.1.0+1
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ^3.0.0

dependencies:
  dart_frog: ^1.1.0
  dart_frog_auth: ^1.1.0
  dart_jsonwebtoken: ^2.13.0

  shelf_cors_headers: ^0.1.5
  json_annotation: ^4.8.1
  logging: ^1.2.0
  equatable: ^2.0.5
  bad_words: ^0.3.0
  uuid: ^4.3.3
  crypto: ^3.0.3

  intl:

dev_dependencies:
  mocktail: ^1.0.3
  test: ^1.19.2
  very_good_analysis: ^5.1.0
  dart_frog_gen: ^2.0.0
  build_runner: ^2.1.4
  json_serializable: ^6.7.1