builders:
  source_rpc:
    import: "package:globe_functions/builders.dart"
    builder_factories: ["sourceRpcBuilder"]
    build_extensions:
      { ".dart": [".server.dart", ".client.dart"] }
    auto_apply: root_package
    build_to: source

  # create_rpc_pipeline:
  #   import: "package:globe_functions/builders.dart"
  #   builder_factories: ["createRpcPipelineBuilder"]
  #   build_extensions:
  #     ".shelf_rpc_spec.json": [".server.dart"]
  #   auto_apply: root_package
  #   build_to: source
  #   target: ":create_rpc_pipeline"
  #   required_inputs: [".shelf_rpc_spec.json"]

  # create_rpc_client:
  #   import: "package:globe_functions/builders.dart"
  #   builder_factories: ["createRpcClientBuilder"]
  #   build_extensions:
  #     ".shelf_rpc_spec.json": [".client.dart"]
  #   auto_apply: root_package
  #   build_to: source
  #   target: ":create_rpc_client"
  #   required_inputs: [".shelf_rpc_spec.json"]

