name: globe_auth
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.0-323.0.dev

# Add regular dependencies here.
dependencies:
  globe_auth_rest_client:
  dio:

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
