name: globe_auth_rest_client
description: A generated rest client for Globe Auth.
version: 0.1.0
repository: https://github.com/invertae/globe

environment:
  sdk: '>=3.7.0-323.0.dev <4.0.0'

# Add regular dependencies here.
dependencies:
  http:

dev_dependencies:
  test: ^1.25.15
