swagger_parser:
  name: globe_auth

  root_client_name: GlobeAuthRestClient

  # Sets the url of the OpenApi schema.
  schema_url: http://localhost:8787/auth/schema.json

  # Required. Sets output directory for generated files (Clients and DTOs).
  output_directory: lib/api