name: globe_tasks
description: Periodic checker for new Flutter/Dart versions.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  args: ^2.4.0
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  http: ^1.1.0
  dotenv: ^4.2.0
  collection: ^1.19.0
  pub_semver: ^2.1.4

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0