name: crud_rest_api_shelf
description: A simple CRUD REST API built with Dart Shelf
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  shelf: ^1.4.2
  shelf_router: ^1.1.3
  shelf_cors_headers: ^0.1.5

dev_dependencies:
  lints: ^3.0.0
