name: dartfrog_jwt_auth
description: A simple dart frog project
version: 0.1.0+1
environment:
  sdk: '>=3.0.0'

dependencies:
  dart_frog: ^1.0.0
  intl: ^0.19.0
  dart_jsonwebtoken: ^2.14.0

  dotenv: ^4.2.0
  bcrypt: ^1.1.3

dev_dependencies:
  test: ^1.25.4
  mocktail: ^1.0.3
  lints: ^3.0.0
  envied_generator: ^0.5.4+1