name: Test Globe CLI Deploy


on:
  pull_request:
    paths:
      - 'packages/globe_cli/**'
    branches:
      - main

env:
  GLOBE: "dart run /packages/globe_cli/bin/globe.dart"

jobs:
  deploy_dart:
    name: Deploy Dart with CLI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
      - uses: bluefireteam/melos-action@v3
      - run: |
          cd ./examples/shelf/
          ${{ env.GLOBE }} deploy --token=${{ secrets.GLOBE_TEST_DEPLOY_TOKEN }} --project="e2e2581f-11ab-40dc-862c-ad1d1fdac4ad"

  deploy_flutter:
    name: Deploy Flutter with CLI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
      - uses: bluefireteam/melos-action@v3
      - run: |
          ${{ env.GLOBE }} deploy --token=${{ secrets.GLOBE_TEST_DEPLOY_TOKEN }} --project="1c73e6b9-6ce4-4a2f-a0a3-1f096d6bc1e5"