name: Test Globe CLI Deploy


on:
  pull_request:
    paths:
      - 'packages/globe_cli/**'
    branches:
      - main

jobs:
  deploy_dart:
    name: Deploy Dart with CLI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
      - uses: bluefireteam/melos-action@v3
      - run: dart run "${{ github.workspace }}/packages/globe_cli/bin/globe.dart"

          # melos globe "deploy --token=${{ secrets.GLOBE_TEST_DEPLOY_TOKEN }} --project="e785cd34-0743-4c4b-a4f7-d7a7c950d2ca""
        # working-directory: ./examples/shelf/


  # deploy_flutter:
  #   name: Deploy Flutter with CLI
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: subosito/flutter-action@v2
  #     - uses: bluefireteam/melos-action@v3
  #     - run: |
  #         melos globe "deploy --token=${{ secrets.GLOBE_TEST_DEPLOY_TOKEN }} --project="1c73e6b9-6ce4-4a2f-a0a3-1f096d6bc1e5""