name: spell_checker

on:
  push:
    branches:
      - main
  pull_request:

# jobs:
#   test:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#       - run: npm -g install cspell
#       - run: ./scripts/cspell-run.sh
#       - run: ./scripts/cspell-verify.sh
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: streetsidesoftware/cspell-action@v5
        with:
          config: ".github/cspell.json"
